[versions]

compile-sdk = "34"
firebase-crashlytics-gradle = "2.9.9"
google-services = "4.4.1"
gradle = "8.5.2"
hilt-android-gradle-plugin = "2.46.1"
kotlin-gradle-plugin = "1.7.20"
ktlint-gradle = "11.5.1"
min-sdk = "21"
target-sdk = "33"
version-code = "20000"
version-name = "2.0.0"

gradle-plugin = "1.7.20"
compose-bom = "2024.03.00"
activity-compose = "1.9.1"
accompanist = "0.30.1"
androidx-junit = "1.2.1"
coil-compose = "2.4.0"
datastore-preferences = "1.0.0"
espresso-core = "3.6.1"
hilt = "2.46.1"
hilt-android = "2.47"
hilt-navigation-compose = "1.0.0"
junit = "4.13.2"
kluent = "1.73"
kotlinx-coroutines-test = "1.7.3"
lifecycle = "2.8.4"
logging-interceptor = "4.11.0"
mockk = "1.13.7"
mockito-core = "5.12.0"
progress-indicator = "0.2.0"
navigation-compose = "2.8.0"
network-response-adapter = "4.1.0"
paging-compose = "3.3.2"
paging-runtime-ktx = "3.3.2"
play-services-ads = "23.3.0"
retrofit = "2.9.0"
room = "2.5.2"
timber = "5.0.1"
toolbar-compose = "2.3.5"
ui-test-junit4 = "1.7.0-beta07"
work-runtime-ktx = "2.8.1"
appcompat = "1.6.1"
androidx-core = "1.13.1"
firebase-bom = "32.3.1"
ksp = "1.7.20-1.0.8"

[libraries]
# Compose
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata" }

lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
# Lifecycle
accompanist-flowlayout = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "accompanist" }
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }
accompanist-pager-indicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanist" }
# Navigation
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
# Hilt
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt-android" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hilt-navigation-compose" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation-compose" }

coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil-compose" }
converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore-preferences" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }

hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hilt-navigation-compose" }
junit = { module = "junit:junit", version.ref = "junit" }
kluent = { module = "org.amshove.kluent:kluent-android", version.ref = "kluent" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines-test" }

lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
lifecycle-livedata = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycle" }

logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "logging-interceptor" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito-core" }
progress-indicator = { module = "com.ehsanmsz:msz-progress-indicator", version.ref = "progress-indicator" }

network-response-adapter = { module = "com.github.haroldadmin:NetworkResponseAdapter", version.ref = "network-response-adapter" }
paging-compose = { module = "androidx.paging:paging-compose", version.ref = "paging-compose" }
paging-runtime-ktx = { module = "androidx.paging:paging-runtime-ktx", version.ref = "paging-runtime-ktx" }
play-services-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "play-services-ads" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }

room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-paging = { module = "androidx.room:room-paging", version.ref = "room" }

timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
toolbar-compose = { module = "me.onebone:toolbar-compose", version.ref = "toolbar-compose" }
ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "ui-test-junit4" }
work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work-runtime-ktx" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
# Firebase
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
remote-config-ktx = { module = "com.google.firebase:firebase-config-ktx" }
crashlytics-ktx = { module = "com.google.firebase:firebase-crashlytics-ktx" }
analytics-ktx = { module = "com.google.firebase:firebase-analytics-ktx" }
# Classpath
firebase-crashlytics-gradle = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "firebase-crashlytics-gradle" }
google-services = { module = "com.google.gms:google-services", version.ref = "google-services" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
hilt-android-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt-android-gradle-plugin" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-gradle-plugin" }
ktlint-gradle = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "ktlint-gradle" }

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

