# https://singhajit.com/android-ci-cd-using-github-actions/
name: CI
on: [ "push" ]

jobs:
  # 1. Fast Compilation (Fail Fast)
  build:
    runs-on: ubuntu-latest
    env:
      OVER_API_KEY: ${{ secrets.OVER_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Compile Project
        run: ./gradlew assembleDebug

  # 2. Static Analysis (Runs in parallel)
  static-analysis:
    needs: [ build ]
    runs-on: ubuntu-latest
    env:
      OVER_API_KEY: ${{ secrets.OVER_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Run Lint & Ktlint
        run: ./gradlew ktlintCheck lint --continue --stacktrace

      - name: Upload static analysis reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: static_analysis_reports
          path: "**/build/reports/lint-results-*"

  # 3. Unit Tests and Coverage
  unit-tests:
    needs: [ build ]
    runs-on: ubuntu-latest
    env:
      OVER_API_KEY: ${{ secrets.OVER_API_KEY }}
      GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx3072m -XX:MaxMetaspaceSize=768m"
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Run unit tests with Kover
        run: ./gradlew test koverXmlReport koverHtmlReport --continue --stacktrace

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: all_unit_test_reports
          path: "**/build/reports/tests/**"

      - name: Upload Kover report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: kover_report
          path: build/reports/kover/

  # 4. Snapshot Tests
  snapshot-tests:
    needs: [ build ]
    runs-on: ubuntu-latest
    env:
      OVER_API_KEY: ${{ secrets.OVER_API_KEY }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Run Snapshot tests
        run: ./gradlew :presentation:testDebugUnitTest -Dpaparazzi.test.verify=true --continue --stacktrace

      - name: Upload Snapshot Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: snapshot_report
          path: |
            presentation/build/reports/tests/testDebugUnitTest/
            presentation/build/snapshot/failures/

  # 5. Mutation Tests (:domain)
  mutation-testing:
    needs: [ build ]
    runs-on: ubuntu-latest
    env:
      OVER_API_KEY: ${{ secrets.OVER_API_KEY }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Mutation Tests (:domain)
        run: ./gradlew :domain:pitest --stacktrace

      - name: Upload Pitest Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mutation_tests
          path: domain/build/reports/pitest/
