name: CI
on: ["push"]

jobs:
  # https://singhajit.com/android-ci-cd-using-github-actions/
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build & deploy Android release
        uses: timheuer/base64-to-file@v1
        id: android_keystore
        with:
          fileName: "android_keystore.keystore"
          encodedString: ${{ secrets.OVER_PROD_STORE_FILE_BASE64 }}
        env:
          OVER_PROD_STORE_FILE: ${{ steps.android_keystore.outputs.filePath }}
          OVER_PROD_PASSWORD: ${{ secrets.OVER_PROD_PASSWORD }}
          OVER_PROD_KEY_ALIAS: ${{ secrets.OVER_PROD_KEY_ALIAS }}

      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
  lint:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run ktlint
        run: ./gradlew ktlintCheck
  unit-test:
    needs: [ lint ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Run unit tests
        run: ./gradlew test

      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: unit_test_report
          path: app/build/reports/tests/testDebugUnitTest/